# Generated by Django 5.2.1 on 2025-05-18 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptorneo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='numero_camiseta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
