# Generated by Django 5.2.2 on 2025-06-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptorneo', '0002_alter_jugador_numero_camiseta'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='partidos'),
        ),
    ]
