# Generated by Django 5.2.3 on 2025-06-16 15:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptorneo', '0003_partido_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
